### ISSUE TITLE
No bin/flex in package

### ISSUE THREAD

**Issue by Quincunx271** [uilianries/conan-flex#1]
Many of the packages do not contain the flex executable.

### Steps to reproduce

```
$ conan install flex/2.6.4@bincrafters/stable
$ ls $(conan info flex/2.6.4@bincrafters/stable --paths | grep flex | grep package_folder | sed 's/\s*package_folder:\s*//')
```

The output doesn't include the `bin` folder, under which `bin/flex` lives.

This installs the package with id [`eeaeee94b6f15f07b3290ce2a162ca2292174e24`][dont], which doesn't have a `bin` folder in its conan_package.tgz, but  the package with id [`6ae331b72e7e265ca2a3d1d8246faf73aa030238`][has] does have it.

This is on an Ubuntu 16.04 machine. Configuration:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

  [dont]: https://bintray.com/version/files/bincrafters/public-conan/flex%3Abincrafters/2.6.4%3Astable?order=asc&sort=name&basePath=bincrafters%2Fflex%2F2.6.4%2Fstable%2F0%2Fpackage%2Feeaeee94b6f15f07b3290ce2a162ca2292174e24%2F0&tab=files
  [has]: https://bintray.com/version/files/bincrafters/public-conan/flex%3Abincrafters/2.6.4%3Astable?order=asc&sort=name&basePath=bincrafters%2Fflex%2F2.6.4%2Fstable%2F0%2Fpackage%2F6ae331b72e7e265ca2a3d1d8246faf73aa030238%2F0&tab=files

**Comment by uilianries** [comment]
Hi @Quincunx271 !

I'm not sure if you are opening an issue for Bincrafters or to my fork.

Anyway, there are two flavors of flex, the library and the installer.

The installer is that you want, the bin folder with the executable. For that, you need to install `flex_installer/2.6.4@bincrafters/stable`

On the other hand, we have the flex package, which contains only the library and headers. To install it you need to use the reference `flex/2.6.4@bincrafters/stable`

Why keep separated? Most of user/developers prefer to use only the library when a project provides executable and libraries. Since Bincrafters maintain a big number of projects, we prefer keep a pattern, which means separate for all projects, otherwise it would be very difficult to track if a project contains or not an executable. Maybe in the future we will change this approach, because as you can see it not intuitive.

If you need to use both flex executable and it libraries, you can install both flex package and flex_installer.

For future issues involving Bincrafters' packages, please open your issue here: https://github.com/bincrafters/community/issues

Best regards.

**Comment by Quincunx271** [comment]
Ahh, thanks. I didn't realize that this was a fork, and I didn't realize that that was how to handle flex_installer vs flex. Thank you.
